### ISSUE TITLE
期末報告

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap#11]
### 期末報告及附件
- [x] 大綱
- [x] 委員意見：預估平台運作費用
- [x] 功能實作與否之緣由 (例如 OI 值之計算及實作)
- [x] 前端測試大綱、情境

#### 附件
- [x] 教育訓練計畫書
- [x] 各階段訪談大綱
- [x] 需求訪談逐字稿
- [ ] 第二期開發項目
- [x] 伺服器環境規格書
- [x] 系統架構
- [x] 系統檢核表
- [x] 系統測試報告書(含弱點掃描與源碼檢測)
- [x] 軟硬體清冊

### 期末報告光碟
- [ ] 期末報告電子檔
- [ ] github上的內容
- [ ] 各階段訪談文字紀錄、逐字稿

### Github內容
- [ ] 開發規劃建議規格說明書
- [ ] 系統設計與分析
- [ ] 美工圖片與程式設計
- [ ] 安裝、測試、訓練、技術文件及產生或開發原始碼之提供。不包含廠商使用之第三人軟體原始碼。

**Comment by g11145590** [comment]
程式碼以公開在Github 的方式交付，若需要實體交付則另備光碟提供，Github中提供項目包含：(a) 開發規劃建議規格說明書，(b) 系統設計與分析，(c) 美工圖片與程式設計，(d) 安裝、測試、訓練、技術文件及產生或開發原始碼之提供。但不包含廠商使用之第三人軟體原始碼。

**Comment by cjk-halodule** [comment]
可否請 @g11145590 調整細節為本次期末報告 11/6 EOB 需要準備好的項目，並整理在最上方？謝謝。
