### ISSUE TITLE
法律諮詢

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap#12]
由於系統將有多個單位的各個角色參與使用，而各單位、計畫的相片資料在使用、分析及資訊公開作為上可能會因為不同的授權及行政規定需要系統協助滿足管理需求，故法律諮詢項目的工作在於確認資料管理及使用的規範是否能保護與相片資料、分析結果相關單位及人員的權益，同時確保規定的細節不至於限制自動相機調查成果在保育政策的制定，或是民間資料加值應用的創意。本團隊未來將就法律諮詢項目的工作結論以清楚的文字準確地在專案系統中列出說明。

**Comment by g11145590** [comment]
提供使用者條款、個人資料保護法、著作權法及創用CC公眾授權之專業諮詢服務。
