### ISSUE TITLE
儲存影片詮釋資料至系統中

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap#28]
透過系統 API 所提供格式及 endpoint 上傳。

包含：
- [ ] 計畫
- [ ] 樣區
- [ ] 相機位置
- [ ] 錄影上傳後的網址
- [ ] 開始時間
- [ ] 片長
- [ ] 播放清單 ID

**Comment by cjk-halodule** [comment]
This depends on #30

**Comment by trashmai** [comment]
簡化為 #34
